#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "Common.h"
#include "Payload.h"

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba32f) uniform image2D colorImage;
layout(set = 0, binding = 2, rgba32f) uniform image2D albedoImage;
layout(set = 0, binding = 3, rgba32f) uniform image2D normalImage;
layout(set = 0, binding = 4) uniform DynamicData { DynamicDataBlock dynamicData; };

layout(location = 0) rayPayloadEXT Payload payload;

void main() 
{
	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
	const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
	vec2 d = inUV * 2.0 - 1.0;

	vec4 origin = dynamicData.viewInverse * vec4(0,0,0,1);
	vec4 target = dynamicData.projInverse * vec4(d.x, d.y, 1, 1);
	vec4 direction = dynamicData.viewInverse*vec4(normalize(target.xyz), 0) ;

	float tmin = 0.001;
	float tmax = 1e32;

	payload.rayOrigin = origin.xyz;
	payload.rayDir = direction.xyz;
	payload.radiance = vec3(0.0);
	payload.albedo = vec3(0.0);
	payload.normal = vec3(0.0);
	payload.attenuation = vec3(1.0);
	payload.rngState = uint(gl_LaunchIDEXT.x * 1973u ^ gl_LaunchIDEXT.y * 9277u ^ 89173u);
	payload.done = 0;
	payload.depth = 0;
    payload.weight = 1.0;

    vec3 color = vec3(0.0);

	for(int depth = 0; depth < 64; depth++)
	{
		traceRayEXT(
			topLevelAS,
			gl_RayFlagsCullBackFacingTrianglesEXT,
			0xff, 0, 0, 0,
			payload.rayOrigin, tmin,
			payload.rayDir, tmax,
			0);
		color += payload.radiance;
		if(payload.done == 1 || length(payload.attenuation) < 0.001)
			break;
	}

	imageStore(colorImage, ivec2(gl_LaunchIDEXT.xy), vec4(color, 0.0));
	imageStore(albedoImage, ivec2(gl_LaunchIDEXT.xy), vec4(payload.albedo, 0.0));
	imageStore(normalImage, ivec2(gl_LaunchIDEXT.xy), vec4(payload.normal, 0.0));
}
