#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "Common.h"
#include "Payload.h"

layout(location = 0) rayPayloadInEXT Payload payload;

hitAttributeEXT vec3 attribs;

// clang-format off
layout(buffer_reference, scalar) buffer Vertices { Vertex v[]; }; // Positions of an object
layout(buffer_reference, scalar) buffer Indices { uvec3 i[]; }; // Triangle indices

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 6) buffer SceneDesc { Mesh i[]; } sceneDesc;
layout(set = 0, binding = 7, scalar) buffer GlobalMaterials { Material i[]; } materials;
// Scene textures
layout(set = 0, binding = 8) uniform sampler2D textures[];
// Emissive objects triangles
layout(set = 0, binding = 9, scalar) buffer EmissiveTriangles {EmissiveTriangle L[];} emissiveTriangles;
// clang-format on

// --------------------------- texture sampling --------------------------------
vec4 sampleBaseColor(const Material m, vec2 uv) {
    vec4 base = m.mBaseColorFactor;
    if(m.mBaseColorTex >= 0) {
        // Base color is typically authored in sRGB; ensure your sampler/format handles sRGB -> linear
        base *= texture(textures[m.mBaseColorTex], uv);
    }
    return base;
}

void main()
{
	// When contructing the TLAS, we stored the model id in InstanceCustomIndexEXT, so the
	// the instance can quickly have access to the data

	// Object data
	Mesh mesh = sceneDesc.i[gl_InstanceCustomIndexEXT];
	Indices indices = Indices(mesh.mIndices);
	Vertices vertices = Vertices(mesh.mVertices);

	//Mesh material
	Material objMat = materials.i[mesh.mMaterialIndex];

	// Indices of the triangle
	uvec3 ind = indices.i[gl_PrimitiveID];

	// Vertex of the triangle
	Vertex v0 = vertices.v[ind.x];
	Vertex v1 = vertices.v[ind.y];
	Vertex v2 = vertices.v[ind.z];

	// Barycentric coordinates of the triangle
	const vec3 barycentrics = vec3(1.0f - attribs.x - attribs.y, attribs.x, attribs.y);

    // Texture coordinates at hit position
	vec2 uv0 = v0.mTC;
	vec2 uv1 = v1.mTC;
	vec2 uv2 = v2.mTC;

	vec2 objUV = uv0 * barycentrics.x + uv1 * barycentrics.y + uv2 * barycentrics.z;

    vec4 baseColor = sampleBaseColor(objMat, objUV);
    float alpha = baseColor.a;

	if(alpha < 0.5 || gl_HitKindEXT == gl_HitKindBackFacingTriangleEXT)
	{
		//payload.radiance += baseColor.rgb * payload.weight * payload.attenuation * alpha;
		// Reduce weight for remaining transparency
		//payload.weight *= (1.0 - alpha);
        // Transparent -> ignore this intersection and keep searching
        ignoreIntersectionEXT;
    }
}